version: "3.8"

services:
  db:
    image: pranithamarri/pyapp:db_image
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    deploy:
      replicas: 1

  auth:
    image: pranithamarri/pyapp:auth_image
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    depends_on:
      - db
    deploy:
      replicas: 1

  book:
    image: pranithamarri/pyapp:book_image
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    depends_on:
      - db
    deploy:
      replicas: 1

  borrow:
    image: pranithamarri/pyapp:borrow_image
    ports:
      - "5003:5003"
    networks:
      - mynetwork
    depends_on:
      - db
    deploy:
      replicas: 1

  frontend:
    image: pranithamarri/pyapp:frontend
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - auth
      - book
      - borrow
    deploy:
      replicas: 1

networks:
  mynetwork:
    driver: overlay
